services:
  web:
    build:
      context: .
      dockerfile: src/ProbHammer.Web/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
    volumes:
      - ./src/ProbHammer.Web/BsData:/app/BsData:ro
      - ./src/ProbHammer.Web/Data:/app/Data:ro
